"""agregar_tabla_cross_sell_rules

Revision ID: 4e3f8332769f
Revises: 7252be42f39a
Create Date: 2026-03-19 23:01:56.076348
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '4e3f8332769f'
down_revision: Union[str, None] = '7252be42f39a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cross_sell_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('trigger_item_id', sa.UUID(), nullable=False),
    sa.Column('suggested_item_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=True),
    sa.Column('discount_pct', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['suggested_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['trigger_item_id'], ['menu_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cross_sell_rules_restaurant_id'), 'cross_sell_rules', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_cross_sell_rules_trigger_item_id'), 'cross_sell_rules', ['trigger_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cross_sell_rules_trigger_item_id'), table_name='cross_sell_rules')
    op.drop_index(op.f('ix_cross_sell_rules_restaurant_id'), table_name='cross_sell_rules')
    op.drop_table('cross_sell_rules')
    # ### end Alembic commands ###
