"""agregar_config_lealtad

Revision ID: ee5071913aef
Revises: 4e3f8332769f
Create Date: 2026-03-19 23:05:43.266127
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'ee5071913aef'
down_revision: Union[str, None] = '4e3f8332769f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants_config', sa.Column('points_reward_rate', sa.Integer(), nullable=False))
    op.add_column('restaurants_config', sa.Column('points_redemption_value', sa.NUMERIC(precision=5, scale=4), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants_config', 'points_redemption_value')
    op.drop_column('restaurants_config', 'points_reward_rate')
    # ### end Alembic commands ###
